# @package datasets.cesnet_quicext25_top50
_target_: eiffel.datasets.preprocessed_network.load_preprocessed_data

task_dir: ${anchor:}/data/cesnet
target_name_column: target_name
target_id_column: target_id
metadata_columns:
  - source_day
  - target_name
  - target_id
exclude_columns:
  - source_day
  - target_name
  - target_id
  - client_id
expected_num_clients: 10
expected_num_classes: 50

key: cesnet_quicext25_top50
_default_target: [ "*" ]
seed: ${seed}
