# @package datasets.ciciot_binary
_target_: eiffel.datasets.preprocessed_network.load_preprocessed_data

task_dir: ${anchor:}/data/ciciot
target_name_column: binary_target
target_id_column: binary_target_id
attack_metadata_column: family_target
metadata_columns:
  - source_file
  - binary_target
  - binary_target_id
  - family_target
  - family_target_id
  - fine_target
  - fine_target_id
exclude_columns:
  - source_file
  - binary_target
  - binary_target_id
  - family_target
  - family_target_id
  - fine_target
  - fine_target_id
  - client_id
expected_num_clients: 10
expected_num_classes: 2

key: ciciot_binary
_default_target: [ DDoS ]
seed: ${seed}
