# @package datasets.ciciot_family
_target_: eiffel.datasets.preprocessed_network.load_preprocessed_data

task_dir: ${anchor:}/data/ciciot
target_name_column: family_target
target_id_column: family_target_id
metadata_columns:
  - source_file
  - binary_target
  - binary_target_id
  - family_target
  - family_target_id
  - fine_target
  - fine_target_id
exclude_columns:
  - source_file
  - binary_target
  - binary_target_id
  - family_target
  - family_target_id
  - fine_target
  - fine_target_id
  - client_id
expected_num_clients: 10
expected_num_classes: 8

key: ciciot_family
_default_target: [ DDoS ]
seed: ${seed}
