# @package datasets.ciciot_fine
_target_: eiffel.datasets.preprocessed_network.load_preprocessed_data

task_dir: ${anchor:}/data/ciciot
target_name_column: fine_target
target_id_column: fine_target_id
metadata_columns:
  - source_file
  - binary_target
  - binary_target_id
  - family_target
  - family_target_id
  - fine_target
  - fine_target_id
exclude_columns:
  - source_file
  - binary_target
  - binary_target_id
  - family_target
  - family_target_id
  - fine_target
  - fine_target_id
  - client_id
expected_num_clients: 10
expected_num_classes: 34

key: ciciot_fine
_default_target: [ "*" ]
seed: ${seed}
